.TH "openni_init.h" 3 "Mon Sep 23 2013" "Version 0.1.2" "OpenNI2 Grabber" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openni_init.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'openni_pcl\&.h'\fP
.br
\fC#include <pcl/visualization/image_viewer\&.h>\fP
.br
\fC#include <pcl/octree/octree\&.h>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBopenni2_grabber\fP"
.br
.RI "\fIOpenNI2 Grabber class\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenNI2 Grabber from the source code\&.
